config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :stockholders
  devise_for :users
  root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :stockholder
end

app/models/stockholder.rb
class Stockholder < ActiveRecord::Base
	has_many :product
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.fetch(:product, {})
    end
end

app/controllers/stockholders_controller.rb
class StockholdersController < ApplicationController
  before_action :set_stockholder, only: [:show, :edit, :update, :destroy]

  # GET /stockholders
  # GET /stockholders.json
  def index
    @stockholders = Stockholder.all
  end

  # GET /stockholders/1
  # GET /stockholders/1.json
  def show
  end

  # GET /stockholders/new
  def new
    @stockholder = Stockholder.new
  end

  # GET /stockholders/1/edit
  def edit
  end

  # POST /stockholders
  # POST /stockholders.json
  def create
    @stockholder = Stockholder.new(stockholder_params)

    respond_to do |format|
      if @stockholder.save
        format.html { redirect_to @stockholder, notice: 'Stockholder was successfully created.' }
        format.json { render :show, status: :created, location: @stockholder }
      else
        format.html { render :new }
        format.json { render json: @stockholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stockholders/1
  # PATCH/PUT /stockholders/1.json
  def update
    respond_to do |format|
      if @stockholder.update(stockholder_params)
        format.html { redirect_to @stockholder, notice: 'Stockholder was successfully updated.' }
        format.json { render :show, status: :ok, location: @stockholder }
      else
        format.html { render :edit }
        format.json { render json: @stockholder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stockholders/1
  # DELETE /stockholders/1.json
  def destroy
    @stockholder.destroy
    respond_to do |format|
      format.html { redirect_to stockholders_url, notice: 'Stockholder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stockholder
      @stockholder = Stockholder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stockholder_params
      params.fetch(:stockholder, {})
      params.require(:stockholder).permit(:stockholder_name,:number_product)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stockholders_helper.rb
module StockholdersHelper
end

app/views/home/index.html.erb
<%= render :partial => "shared/header" %>

<div class="ui segment">
	
Hello Welcome to easy shopper, <%= current_user %>
</div>
		     
<div class="ui inverted vertical footer segment">
    <div class="ui center aligned container">
<div class="inline field" style="margin-bottom: 20px;">
<i class="twitter large icon"></i>
<i class="vine large icon"></i>
<i class="facebook large icon"></i>
<i class="whatsapp large icon"></i>
</div>
      <div class="ui stackable inverted divided grid">
        <div class="three wide column">
          <h4 class="ui inverted header">Group 1</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Link One</a>
            <a href="#" class="item">Link Two</a>
            <a href="#" class="item">Link Three</a>
            <a href="#" class="item">Link Four</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Group 2</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Link One</a>
            <a href="#" class="item">Link Two</a>
            <a href="#" class="item">Link Three</a>
            <a href="#" class="item">Link Four</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Group 3</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Link One</a>
            <a href="#" class="item">Link Two</a>
            <a href="#" class="item">Link Three</a>
            <a href="#" class="item">Link Four</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
      <div class="ui inverted section divider"></div>
     
      <div class="ui horizontal inverted small divided link list">
        <a class="item" href="#">Site Map</a>
        <a class="item" href="#">Contact Us</a>
        <a class="item" href="#">Terms and Conditions</a>
        <a class="item" href="#">Privacy Policy</a>
      </div>
    </div>
  </div>

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Easyshopp
		=stylesheet_link_tag 'application', :media =>'all'
		=javascript_include_tag 'application'
		=csrf_meta_tag

	%body
		=if notice
			.notice
				=notice
		=if alert
			.alert
				=alert

		=yield



		  
		  

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_header.html.haml
.ui.inverted.masthead.centered.segment
	.ui.page.grid
		.column
			.ui.secondary.pointing.menu
				= link_to "Easyshopp", root_path ,:class=>"logo item" 
				= link_to "Home" ,root_path , :class=> "active item"
				= link_to "Stockholders" ,stockholders_path , :class=>"item"
				= link_to "About","" , :class=>"item"
				= link_to "Contact", '' ,:class=>"item"
				-if user_signed_in?
					= link_to "Settings", edit_user_registration_path ,:class=>"item"
					= link_to "Profile", "" ,:class=>"item"
			    
				.right.menu
					.item
						-if user_signed_in?
							=link_to 'Log Out', destroy_user_session_path, method: 'delete', class: 'ui item'
						-else
							=link_to 'Log In', new_user_session_path, class: 'ui item'

app/views/stockholders/_form.html.erb
<%= form_for(@stockholder) do |f| %>
  <% if @stockholder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stockholder.errors.count, "error") %> prohibited this stockholder from being saved:</h2>

      <ul>
      <% @stockholder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       
        
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :stockholder_name %><br />
    <%= f.text_field :stockholder_name, autofocus: true ,:placeholder=>"Stockholder" %>

  <div class="actions">
    <%= f.submit :class=>"ui blue button"%>
  </div>
<% end %>

app/views/stockholders/edit.html.erb
<h1>Editing Stockholder</h1>

<%= render 'form' %>

<%= link_to 'Show', @stockholder %> |
<%= link_to 'Back', stockholders_path %>

app/views/stockholders/index.html.erb
<%= render :partial => "shared/header" %>

<p id="notice"><%= notice %></p>
  <%if user_signed_in? %> 
<center><h1 class="ui black header">Listing Stockholders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stockholders.each do |stockholder| %>
   
      <tr>
        <td><%= stockholder.stockholder_name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', stockholder ,:class => "ui green button"%></td>
        <td><%= link_to 'Edit', edit_stockholder_path(stockholder), :class=>"ui blue button"%></td>
        <td><%= link_to 'Destroy', stockholder, :class=>"ui red button",method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stockholder', new_stockholder_path ,:class=>"ui black button"%></center>
<%else%>
<center>"Please sign in to view this page :)<br><br>
<%= link_to 'Log In', new_user_session_path, :class =>'ui red button' %></center>
<% end %>

app/views/stockholders/new.html.erb
<%= render :partial => "shared/header" %>
<center><h1 class="ui black header">New Stockholder</h1>

<%= render 'form' %>

<%= link_to 'Back', stockholders_path ,:class=>"ui blue button" %></center>

app/views/stockholders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stockholder_path(@stockholder) %> |
<%= link_to 'Back', stockholders_path %>